config-version: '${main_config_version}'

debug: true

storage-config:
  type: SQLITE
  host: "127.0.0.1"
  port: 3306
  table-prefix: "zvaults_"
  database: "zvaults"
  username: "root"
  password: ""

# This option is use to enable or disable the multi server sync support
# If you enable this option, you need to configure the redis_config section
# If you disable this option, the plugin will not share all actions between all servers using the same redis server
multi_server_sync_support: false

redis_config:
  host: "localhost"
  port: 6379
  password: ""
  user: ""