########################################################################################################################
#
#  ███████╗██╗░░░██╗░█████╗░██╗░░░██╗██╗░░░░░████████╗░██████╗
#  ╚════██║██║░░░██║██╔══██╗██║░░░██║██║░░░░░╚══██╔══╝██╔════╝
#  ░░███╔═╝╚██╗░██╔╝███████║██║░░░██║██║░░░░░░░░██║░░░╚█████╗░
#  ██╔══╝░░░╚████╔╝░██╔══██║██║░░░██║██║░░░░░░░░██║░░░░╚═══██╗
#  ███████╗░░╚██╔╝░░██║░░██║╚██████╔╝███████╗░░░██║░░░██████╔╝
#  ╚══════╝░░░╚═╝░░░╚═╝░░╚═╝░╚═════╝░╚══════╝░░░╚═╝░░░╚═════╝░
#
# Documentation: https://zvaults.groupez.dev/
#
########################################################################################################################

config-version: '${main_config_version}'

# This option is use to configure the level of debuggin in console.
# If you want support please enable it and send the logs to the support
debug: true

# This option is use to configure the storage system
# You can choose between SQLITE and MYSQL
storage-config:
  type: SQLITE
  host: "127.0.0.1"
  port: 3306
  table-prefix: "zvaults_"
  database: "zvaults"
  username: "root"
  password: ""

# This option permits you to configure aliases for the command
command-aliases:
  - "vault"
  - "vaults"
  - "zvault"

# This option is use to enable or disable the multi server sync support
# If you enable this option, you need to configure the redis_config section
# If you disable this option, the plugin will not share all actions between all servers using the same redis server
multi-server-sync-support: false

# This option is use to configure the redis server
redis-config:
  host: "localhost"
  port: 6379
  password: ""
  user: ""