config-version: '${main_config_version}'

debug: true

storage-config:
  type: SQLITE
  host: "127.0.0.1"
  port: 3306
  table-prefix: "zvaults_"
  database: "zvaults"
  username: "root"
  password: ""

multi_server_sync_support: true

redis_config:
  host: "localhost"
  port: 6379
  password: ""
  user: ""