name: zVaults
version: '${version}'
main: fr.traqueur.vaults.ZVaultsPlugin
api-version: '1.20'
author: Traqueur
depend: [zMenu]
libraries:
  - 'redis.clients:jedis:5.2.0'
  - 'dev.dejvokep:boosted-yaml:1.3.6'
  - 'net.kyori:adventure-api:4.17.0'
  - 'net.kyori:adventure-text-minimessage:4.17.0'
  - 'net.kyori:adventure-platform-bukkit:4.3.4'
