name: "&8ᴄᴏɴғɪɢᴜʀᴀᴛɪᴏɴ"
size: 27
items:
  invite:
    type: ZVAULTS_INVITE_PLAYER
    permission: "zvaults.invite"
    item:
      material: EMERALD
      name: "#92bed8ᴍᴀɴᴀɢᴇ ᴀᴄᴄᴇss ᴛᴏ ᴠᴀᴜʟᴛ"
      lore:
        - "#92bed8ʀɪɢʜᴛ ᴄʟɪᴄᴋ &7ᴛᴏ ɪɴᴠɪᴛᴇ ᴘʟᴀʏᴇʀ"
        - ""
        - "#92bed8ʟᴇғᴛ ᴄʟɪᴄᴋ &7ᴛᴏ ᴍᴀɴᴀɢᴇ ᴡʜᴏ ʜᴀᴠᴇ ᴀᴄᴄᴇss"
    slot: 10
    else:
      item:
        material: BARRIER
  customize:
    type: ZVAULTS_CUSTOMIZE_ICON
    permission: "zvaults.customize.icon"
    slot: 12
    item:
      material: NETHER_STAR
      name: "#92bed8ᴄᴜsᴛᴏᴍɪᴢᴇ ɪᴄᴏɴ"
      lore:
        - ""
        - "#92bed8ᴄʟɪᴄᴋ &7ᴛᴏ ᴄʜᴀɴɢᴇ ɪᴄᴏɴ ᴏғ ᴠᴀᴜʟᴛ"
  autopickup:
    type: ZVAULTS_TOGGLE_AUTO_PICKUP
    permission: "zvaults.toggle.auto_pickup"
    slot: 14
    refreshOnClick: true
    item:
      material: HOPPER
      name: "#92bed8ᴀᴜᴛᴏ ᴘɪᴄᴋᴜᴘ"
      lore:
        - "#92bed8ᴄᴜʀʀᴇɴᴛʟʏ &7%autopickup%"
        - "#92bed8ᴄʟɪᴄᴋ &7ᴛᴏ ᴛᴏɢɢʟᴇ ᴀᴜᴛᴏ ᴘɪᴄᴋᴜᴘ"
  delete:
    type: ZVAULTS_DELETE
    permission: "zvaults.delete"
    slot: 16
    item:
      material: REDSTONE_BLOCK
      name: "#92bed8ᴅᴇʟᴇᴛᴇ ᴠᴀᴜʟᴛ"
      lore:
        - ""
        - "#92bed8ᴄʟɪᴄᴋ &7ᴛᴏ ᴅᴇʟᴇᴛᴇ ᴠᴀᴜʟᴛ"
  close:
    type: ZVAULTS_VAULT_CONFIG_CLOSE
    isPermanent: true
    slot: 22
    item:
      material: BARRIER
      name: "&cClose"
  change_name:
    type: ZVAULTS_NAME_MODIFIER
    permission: "zvaults.modify.name"
    slot: 17
    item:
      material: NAME_TAG
      name: "#92bed8ᴄʜᴀɴɢᴇ ɴᴀᴍᴇ"
      lore:
        - ""
        - "#92bed8ᴄʟɪᴄᴋ &7ᴛᴏ ᴄʜᴀɴɢᴇ ɴᴀᴍᴇ"