name: "&8ᴄᴏɴғɪɢᴜʀᴀᴛɪᴏɴ"
size: 27
items:
  invite:
    type: ZVAULTS_INVITE_PLAYER
    permission: "zvaults.invite"
    item:
      material: EMERALD
      name: "#92bed8ᴍᴀɴᴀɢᴇ ᴀᴄᴄᴇss ᴛᴏ ᴠᴀᴜʟᴛ"
      lore:
        - "#92bed8ʀɪɢʜᴛ ᴄʟɪᴄᴋ &7ᴛᴏ ɪɴᴠɪᴛᴇ ᴘʟᴀʏᴇʀ"
        - ""
        - "#92bed8ʟᴇғᴛ ᴄʟɪᴄᴋ &7ᴛᴏ ᴍᴀɴᴀɢᴇ ᴡʜᴏ ʜᴀᴠᴇ ᴀᴄᴄᴇss"
    slot: 10
    else:
      item:
        material: BARRIER
  customize:
    type: ZVAULTS_CUSTOMIZE_ICON
    permission: "zvaults.customize.icon"
    slot: 12
    item:
      material: NETHER_STAR
      name: "#92bed8ᴄᴜsᴛᴏᴍɪᴢᴇ ɪᴄᴏɴ"
      lore:
        - ""
        - "#92bed8ᴄʟɪᴄᴋ &7ᴛᴏ ᴄʜᴀɴɢᴇ ɪᴄᴏɴ ᴏғ ᴠᴀᴜʟᴛ"
  delete:
    type: ZVAULTS_DELETE
    permission: "zvaults.delete"
    slot: 16
    item:
      material: REDSTONE_BLOCK
      name: "#92bed8ᴅᴇʟᴇᴛᴇ ᴠᴀᴜʟᴛ"
      lore:
        - ""
        - "#92bed8ᴄʟɪᴄᴋ &7ᴛᴏ ᴅᴇʟᴇᴛᴇ ᴠᴀᴜʟᴛ"